name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # This triggers the workflow when you push to the main branch.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Make sure this is the Node.js version you're using.

      - name: Install dependencies
        run: |
          npm install

      - name: Build
        run: |
          npm run build  # If you use a different build command, replace this.

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.1.0
        with:
          branch: gh-pages  # This specifies the branch where the built site will be deployed.
          folder: build     # This is the folder that contains your production build (adjust if necessary).
